"""parenting values

Revision ID: 18d4663fd949
Revises: 9d344b799f53
Create Date: 2026-08-11 10:49:26.400438

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "18d4663fd949"
down_revision: Union[str, None] = "9d344b799f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parenting_values_history",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("warmth_score", sa.Float(), nullable=False),
        sa.Column("control_score", sa.Float(), nullable=False),
        sa.Column(
            "type_label",
            sa.Enum("AUTHORITATIVE", "AUTHORITARIAN", "PERMISSIVE", "NEGLECTFUL", name="parenting_type_label_enum"),
            nullable=False,
        ),
        sa.Column("source", sa.Enum("QUESTIONNAIRE", "NARRATIVE", name="parenting_values_source_enum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parenting_values_history_user_id"), "parenting_values_history", ["user_id"], unique=False)
    op.create_table(
        "parenting_values_profiles",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("warmth_score", sa.Float(), nullable=False),
        sa.Column("control_score", sa.Float(), nullable=False),
        sa.Column(
            "type_label",
            sa.Enum("AUTHORITATIVE", "AUTHORITARIAN", "PERMISSIVE", "NEGLECTFUL", name="parenting_type_label_enum"),
            nullable=False,
        ),
        sa.Column("narrative", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parenting_values_profiles")
    op.drop_index(op.f("ix_parenting_values_history_user_id"), table_name="parenting_values_history")
    op.drop_table("parenting_values_history")
    # ### end Alembic commands ###
