"""work_schedule

Revision ID: 80ee98f59f34
Revises: 18d4663fd949
Create Date: 2026-08-11 13:40:08.705348

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "80ee98f59f34"
down_revision: Union[str, None] = "18d4663fd949"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_schedules",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("slot_bitmask", sa.BigInteger(), nullable=False),
        sa.Column(
            "shift_template", sa.Enum("DAY", "EVENING", "NIGHT", "OFF", name="shift_template_enum"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "work_date", name="uq_work_schedule_user_date"),
    )
    op.create_index(op.f("ix_work_schedules_user_id"), "work_schedules", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_schedules_user_id"), table_name="work_schedules")
    op.drop_table("work_schedules")
    # ### end Alembic commands ###
