"""guardian profile

Revision ID: 9d344b799f53
Revises: ff9d99f5db23
Create Date: 2026-08-11 09:49:26.667273

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9d344b799f53"
down_revision: Union[str, None] = "ff9d99f5db23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guardian_profiles",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("residence_h3", sa.String(length=15), nullable=False),
        sa.Column(
            "job_category",
            sa.Enum(
                "OFFICE_WORKER",
                "SERVICE",
                "SELF_EMPLOYED",
                "HEALTHCARE",
                "EDUCATION",
                "IT",
                "PUBLIC_SERVANT",
                "HOMEMAKER",
                "FREELANCER",
                "OTHER",
                name="job_category_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "work_type",
            sa.Enum(
                "FULL_TIME", "SHIFT", "FLEXIBLE", "REMOTE", "FREELANCE", "UNEMPLOYED", "OTHER", name="work_type_enum"
            ),
            nullable=False,
        ),
        sa.Column(
            "household_composition",
            sa.Enum("TWO_PARENT", "SINGLE_PARENT", "EXTENDED_FAMILY", "OTHER", name="household_composition_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_guardian_profiles_residence_h3"), "guardian_profiles", ["residence_h3"], unique=False)
    op.create_table(
        "guardian_tags",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("tag_code", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tag_code", name="uq_guardian_tag_user_code"),
    )
    op.create_index(op.f("ix_guardian_tags_user_id"), "guardian_tags", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_guardian_tags_user_id"), table_name="guardian_tags")
    op.drop_table("guardian_tags")
    op.drop_index(op.f("ix_guardian_profiles_residence_h3"), table_name="guardian_profiles")
    op.drop_table("guardian_profiles")
    # ### end Alembic commands ###
