"""care_session

Revision ID: a1f3c9d0e2b6
Revises: 80ee98f59f34
Create Date: 2026-08-11 14:20:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1f3c9d0e2b6"
down_revision: Union[str, None] = "80ee98f59f34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "care_sessions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("requester_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("provider_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("care_date", sa.Date(), nullable=False),
        sa.Column("start_slot", sa.SmallInteger(), nullable=False),
        sa.Column("end_slot", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("REQUESTED", "CONFIRMED", "REJECTED", name="care_session_status_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["provider_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_care_sessions_requester_id"), "care_sessions", ["requester_id"], unique=False)
    op.create_index(op.f("ix_care_sessions_provider_id"), "care_sessions", ["provider_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_care_sessions_provider_id"), table_name="care_sessions")
    op.drop_index(op.f("ix_care_sessions_requester_id"), table_name="care_sessions")
    op.drop_table("care_sessions")
    # ### end Alembic commands ###
