"""care_checkin_journal

Revision ID: b7e4d1a08c53
Revises: a1f3c9d0e2b6
Create Date: 2026-08-11 15:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7e4d1a08c53"
down_revision: Union[str, None] = "a1f3c9d0e2b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "care_sessions",
        sa.Column("child_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    )
    op.add_column("care_sessions", sa.Column("meeting_h3", sa.String(length=15), nullable=False))
    op.add_column("care_sessions", sa.Column("checkin_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("care_sessions", sa.Column("checkin_distance_m", sa.Float(), nullable=True))
    op.add_column(
        "care_sessions",
        sa.Column("checkin_out_of_range", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("care_sessions", sa.Column("checkin_reason", sa.String(length=500), nullable=True))
    op.add_column("care_sessions", sa.Column("checkout_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("care_sessions", sa.Column("actual_minutes", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_care_sessions_child_id"), "care_sessions", ["child_id"], unique=False)
    op.create_foreign_key(
        "fk_care_sessions_child_id_children",
        "care_sessions",
        "children",
        ["child_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.create_table(
        "care_logs",
        sa.Column("session_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("meal", sa.String(length=500), nullable=True),
        sa.Column("sleep", sa.String(length=500), nullable=True),
        sa.Column("mood", sa.String(length=50), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("allergy_note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["care_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("care_logs")

    op.drop_constraint("fk_care_sessions_child_id_children", "care_sessions", type_="foreignkey")
    op.drop_index(op.f("ix_care_sessions_child_id"), table_name="care_sessions")
    op.drop_column("care_sessions", "actual_minutes")
    op.drop_column("care_sessions", "checkout_at")
    op.drop_column("care_sessions", "checkin_reason")
    op.drop_column("care_sessions", "checkin_out_of_range")
    op.drop_column("care_sessions", "checkin_distance_m")
    op.drop_column("care_sessions", "checkin_at")
    op.drop_column("care_sessions", "meeting_h3")
    op.drop_column("care_sessions", "child_id")
    # ### end Alembic commands ###
