"""trust_level_fsm

Revision ID: d3f6a2c9e8b1
Revises: c2d5e9f7a1b4
Create Date: 2026-08-11 18:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3f6a2c9e8b1"
down_revision: Union[str, None] = "c2d5e9f7a1b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trust_relationships",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_a_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_b_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("joint_session_count", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_a_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_b_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_a_id", "user_b_id", name="uq_trust_relationship_pair"),
    )
    op.create_index(op.f("ix_trust_relationships_user_a_id"), "trust_relationships", ["user_a_id"], unique=False)
    op.create_index(op.f("ix_trust_relationships_user_b_id"), "trust_relationships", ["user_b_id"], unique=False)

    op.create_table(
        "trust_level_history",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("relationship_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("previous_level", sa.String(length=2), nullable=False),
        sa.Column("new_level", sa.String(length=2), nullable=False),
        sa.Column("changed_by_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["relationship_id"], ["trust_relationships.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trust_level_history_relationship_id"), "trust_level_history", ["relationship_id"], unique=False
    )

    op.create_table(
        "joint_care_sessions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("initiator_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("partner_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("place", sa.String(length=100), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("confirmed_by_initiator", sa.Boolean(), nullable=False),
        sa.Column("confirmed_by_partner", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["initiator_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["partner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_joint_care_sessions_initiator_id"), "joint_care_sessions", ["initiator_id"], unique=False)
    op.create_index(op.f("ix_joint_care_sessions_partner_id"), "joint_care_sessions", ["partner_id"], unique=False)

    op.create_table(
        "trust_settings",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("required_joint_count", sa.SmallInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trust_settings")
    op.drop_index(op.f("ix_joint_care_sessions_partner_id"), table_name="joint_care_sessions")
    op.drop_index(op.f("ix_joint_care_sessions_initiator_id"), table_name="joint_care_sessions")
    op.drop_table("joint_care_sessions")
    op.drop_index(op.f("ix_trust_level_history_relationship_id"), table_name="trust_level_history")
    op.drop_table("trust_level_history")
    op.drop_index(op.f("ix_trust_relationships_user_b_id"), table_name="trust_relationships")
    op.drop_index(op.f("ix_trust_relationships_user_a_id"), table_name="trust_relationships")
    op.drop_table("trust_relationships")
    # ### end Alembic commands ###
