"""auth_kit + children 초기 스키마

Revision ID: ff9d99f5db23
Revises:
Create Date: 2026-08-11 04:45:39.923932

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import security_kit.crypto


# revision identifiers, used by Alembic.
revision: str = "ff9d99f5db23"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_email_verification_email_verified", "email_verification_tokens", ["email", "verified_at"], unique=False
    )
    op.create_table(
        "oauth_nonces",
        sa.Column("nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("nonce_hash"),
    )
    op.create_index(op.f("ix_oauth_nonces_created_at"), "oauth_nonces", ["created_at"], unique=False)
    op.create_table(
        "phone_verification_tokens",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_phone_verification_hash_verified", "phone_verification_tokens", ["phone_hash", "verified_at"], unique=False
    )
    op.create_table(
        "sanctioned_identities",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sanctioned_identities_phone_hash"), "sanctioned_identities", ["phone_hash"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("name", security_kit.crypto.EncryptedStr(length=512), nullable=True),
        sa.Column("nickname", sa.String(length=12), nullable=False),
        sa.Column("phone_number", security_kit.crypto.EncryptedStr(length=512), nullable=True),
        sa.Column("phone_hash", sa.String(length=64), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.Enum("M", "F", name="gender_enum"), nullable=True),
        sa.Column(
            "onboarding_status",
            sa.Enum("pending", "terms_agreed", "profile_required", "completed", name="onboarding_status_enum"),
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_sanctioned", sa.Boolean(), nullable=False),
        sa.Column("sanction_reason", sa.String(length=500), nullable=True),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_index(op.f("ix_users_phone_hash"), "users", ["phone_hash"], unique=False)
    op.create_index(op.f("ix_users_purge_at"), "users", ["purge_at"], unique=False)
    op.create_table(
        "children",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("months_old", sa.Integer(), nullable=False),
        sa.Column("gender", sa.Enum("M", "F", name="child_gender_enum"), nullable=False),
        sa.Column("temperament_memo", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_children_user_id"), "children", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("jti", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "social_accounts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "provider", sa.Enum("local", "google", "kakao", "naver", "apple", name="auth_provider_enum"), nullable=False
        ),
        sa.Column("provider_uid", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_uid", name="uq_social_provider_uid"),
    )
    op.create_index(op.f("ix_social_accounts_user_id"), "social_accounts", ["user_id"], unique=False)
    op.create_table(
        "terms_agreements",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("terms_type", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("agreed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "terms_type", name="uq_agreement_user_type"),
    )
    op.create_index(op.f("ix_terms_agreements_user_id"), "terms_agreements", ["user_id"], unique=False)
    op.create_table(
        "children_sensitive",
        sa.Column("child_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("allergies", security_kit.crypto.EncryptedStr(length=512), nullable=True),
        sa.Column("conditions", security_kit.crypto.EncryptedStr(length=512), nullable=True),
        sa.Column("medications", security_kit.crypto.EncryptedStr(length=512), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("child_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("children_sensitive")
    op.drop_index(op.f("ix_terms_agreements_user_id"), table_name="terms_agreements")
    op.drop_table("terms_agreements")
    op.drop_index(op.f("ix_social_accounts_user_id"), table_name="social_accounts")
    op.drop_table("social_accounts")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_children_user_id"), table_name="children")
    op.drop_table("children")
    op.drop_index(op.f("ix_users_purge_at"), table_name="users")
    op.drop_index(op.f("ix_users_phone_hash"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sanctioned_identities_phone_hash"), table_name="sanctioned_identities")
    op.drop_table("sanctioned_identities")
    op.drop_index("ix_phone_verification_hash_verified", table_name="phone_verification_tokens")
    op.drop_table("phone_verification_tokens")
    op.drop_index(op.f("ix_oauth_nonces_created_at"), table_name="oauth_nonces")
    op.drop_table("oauth_nonces")
    op.drop_index("ix_email_verification_email_verified", table_name="email_verification_tokens")
    op.drop_table("email_verification_tokens")
    # ### end Alembic commands ###
